server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///springboot?useSSL=false #数据库如果不用校验的话,就设置成false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
mybatis:
  type-aliases-package: com.atguigu.pojo